### ISSUE TITLE
请问一下nacos server的版本是否会影响到该示例的演示

### ISSUE THREAD

**Issue by nobt854** [fescar-group/fescar-samples#49]
`Caused by: java.lang.ClassNotFoundException: com.alibaba.dubbo.registry.support.AbstractRegistryFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more`

服务我下载的nacos发行的最新版0.9.0(Feb 28, 2019)

**Comment by nobt854** [comment]
test
