### ISSUE TITLE
调用/business/dubbo/buy 模拟下单，执行扣减库存时，fescar-server报错

### ISSUE THREAD

**Issue by chengpei** [fescar-group/fescar-samples#78]
2019-04-02 08:51:09.659 INFO [ServerHandlerThread_51_500]c.a.fescar.core.rpc.DefaultServerMessageListenerImpl.onRegRmMessage:113 -rm register success,message:RegisterRMRequest{resourceIds='jdbc:mysql://127.0.0.1:3306/db_gts_fescar?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true', applicationId='storage-gts-fescar-example', transactionServiceGroup='my_test_tx_group'},channel:[id: 0x478fc3e9, L:/10.8.2.25:8091 - R:/10.8.2.25:4243]
2019-04-02 08:51:09.660 ERROR[NettyServerNIOWorker_6_8]com.alibaba.fescar.core.rpc.netty.MessageCodecHandler.decode:190 -decode error
java.nio.BufferUnderflowException: null
        at java.nio.Buffer.nextGetIndex(Buffer.java:506)
        at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:361)
        at com.alibaba.fescar.core.protocol.transaction.BranchRegisterRequest.decode(BranchRegisterRequest.java:205)
        at com.alibaba.fescar.core.protocol.MergedWarpMessage.doDecode(MergedWarpMessage.java:101)
        at com.alibaba.fescar.core.protocol.MergedWarpMessage.decode(MergedWarpMessage.java:92)
        at com.alibaba.fescar.core.rpc.netty.MessageCodecHandler.decode(MessageCodecHandler.java:177)
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)

**Comment by fengyajing** [comment]
我的确实是报错了，准备换个低版本的fescar-server试试

**Comment by xinchenyixian** [comment]
服务版本要和本地依赖版本对应，示例是0.2.1的
/springboot-dubbo-fescar/pom.xml中<fescar.version>改一下就好了

**Comment by chengpei** [comment]
> 服务版本要和本地依赖版本对应，示例是0.2.1的
> /springboot-dubbo-fescar/pom.xml中<fescar.version>改一下就好了

谢谢，换成0.4.1 就好了

**Comment by wowtrxqn** [comment]
下单成功，订单和库存没减，账户倒是扣了。。。。。

**Comment by justein** [comment]
@wowtrxqn 同样的问题
